"""
Data models for Daily Insight Agent.

WHY THIS FILE EXISTS:
- Defines the universal data structure that ALL sources are normalized into
- Makes it easy for agents to work with data without knowing the original source
- Uses Python dataclasses + Pydantic for type safety

HOW IT RELATES TO AGENT THINKING:
- Agents need a predictable interface to data
- This schema is the "contract" between collectors and agents
- Enables agents to focus on analysis, not data parsing

HOW TO EXTEND:
- Add new fields to ContentItem if you track new metadata
- Create new enums for new source types (e.g., LINKEDIN, PODCAST)
- Add validation logic (e.g., min content length)
"""

from dataclasses import dataclass, asdict
from enum import Enum
from datetime import datetime
from typing import Optional, List, Dict, Any
import hashlib
import json


class SourceType(str, Enum):
    """All possible data sources."""
    DIARY = "diary"
    WHATSAPP = "whatsapp"
    RSS = "rss"
    GOALS = "goals"
    YOUTUBE = "youtube"
    TELEGRAM = "telegram"
    LINKEDIN = "linkedin"
    # Extension points for future sources:
    # LINKEDIN = "linkedin"
    # PODCAST = "podcast"
    # EMAIL = "email"


@dataclass
class ContentItem:
    """
    Universal data structure for all content sources.
    
    This is the KEY to agent architecture:
    - Diary entry → ContentItem
    - WhatsApp message → ContentItem
    - RSS article → ContentItem
    - Goal statement → ContentItem
    
    Agents don't care about source details; they work with ContentItem.
    """
    
    source: SourceType
    title: str
    content: str
    author: str
    timestamp: datetime
    url: Optional[str] = None
    raw_path: Optional[str] = None
    
    def compute_hash(self) -> str:
        """
        Compute unique hash to detect duplicates.
        
        DEDUPLICATION LOGIC:
        - Hash based on content + timestamp (not exact content match)
        - Prevents same diary entry from being stored twice
        - Used by deduplicate.py service
        """
        hash_input = f"{self.source}:{self.content}:{self.author}:{self.timestamp}"
        return hashlib.md5(hash_input.encode()).hexdigest()
    
    def to_dict(self) -> dict:
        """Convert to dictionary for JSON serialization."""
        data = asdict(self)
        data["source"] = self.source.value
        data["timestamp"] = self.timestamp.isoformat()
        data["hash"] = self.compute_hash()
        return data
    
    def to_json(self) -> str:
        """Convert to JSON string."""
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=2)


@dataclass
class DailyInsight:
    """
    The final output structure from the daily pipeline.
    
    This is what gets displayed to the user.
    Generated by coach_agent.py, stored in SQLite, rendered as HTML.
    """
    
    date: str  # YYYY-MM-DD
    main_insight: str  # High-level summary of the day's learnings
    source_summary: str  # What did Reader Agent learn?
    self_reflection: str  # What did Reflection Agent observe about you?
    thinking_biases_detected: List[Dict[str, Any]]  # Specific cognitive biases noticed (objects with name/evidence)
    practical_tip: str  # Concrete, actionable advice
    one_day_action: str  # Something you can do TODAY
    possible_project_idea: Optional[str]  # Optional innovation/project idea
    important_quotes: List[dict]  # [{"quote": "...", "source": "..."}]
    uncertainties: List[str]  # What we're not sure about
    sources_used: List[str]  # Which sources contributed
    
    def to_dict(self) -> dict:
        """Convert to dictionary for JSON/database storage."""
        return asdict(self)
    
    def to_json(self) -> str:
        """Convert to JSON string."""
        return json.dumps(self.to_dict(), ensure_ascii=False, indent=2)


@dataclass
class AgentInput:
    """Input data structure passed to each agent."""
    
    new_items: List[ContentItem]  # Items collected today
    goals: Optional[str]  # Goals file content
    recent_diary: Optional[str]  # Recent diary entries
    previous_insights: Optional[List[DailyInsight]]  # For context
    previous_insight_summaries: Optional[List[str]] = None  # Remote or historical summaries
